// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9WTsFGCyK3I_VCIBFwSQzfnsgzcYrog',
    appId: '1:365414115478:web:8019f7f7bf67a7bd7dbab7',
    messagingSenderId: '365414115478',
    projectId: 'todo-list-acc11',
    authDomain: 'todo-list-acc11.firebaseapp.com',
    storageBucket: 'todo-list-acc11.firebasestorage.app',
    measurementId: 'G-G7WME3HDX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRqvL0FCukhuLoUD2tqLyir1aSxa0cuI',
    appId: '1:365414115478:android:c491753621be37cb7dbab7',
    messagingSenderId: '365414115478',
    projectId: 'todo-list-acc11',
    storageBucket: 'todo-list-acc11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SmaZ16AnSymwQkzdg9RpWBAPSpD3AkM',
    appId: '1:365414115478:ios:60be2bc0a46c4f897dbab7',
    messagingSenderId: '365414115478',
    projectId: 'todo-list-acc11',
    storageBucket: 'todo-list-acc11.firebasestorage.app',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-SmaZ16AnSymwQkzdg9RpWBAPSpD3AkM',
    appId: '1:365414115478:ios:60be2bc0a46c4f897dbab7',
    messagingSenderId: '365414115478',
    projectId: 'todo-list-acc11',
    storageBucket: 'todo-list-acc11.firebasestorage.app',
    iosBundleId: 'com.example.listaDeTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9WTsFGCyK3I_VCIBFwSQzfnsgzcYrog',
    appId: '1:365414115478:web:6df8469c9d961f677dbab7',
    messagingSenderId: '365414115478',
    projectId: 'todo-list-acc11',
    authDomain: 'todo-list-acc11.firebaseapp.com',
    storageBucket: 'todo-list-acc11.firebasestorage.app',
    measurementId: 'G-TSWTR4SSM3',
  );
}
